### ISSUE TITLE
Which checkpoints are correct

### ISSUE THREAD

**Issue by shkarupa-alex** [DingXiaoH/RepLKNet-pytorch#1]
Right now there are multiple checkpoints for some models trained on imagenet1k:
RepLKNet-31B | 224x224
RepLKNet-31B | 384x384

E.g. https://www.evernote.com/l/AS_rHS0dS-hHpJxKoCY-EPvXh1U8w4HJFpc

Which of them should be used?

**Comment by DingXiaoH** [comment]
One of them is pretrained on ImageNet-1K and the other is first pretrained on ImageNet-22K then finetuned on 1K. Will clarify it. Thanks~
