### ISSUE TITLE
Is DepthWiseConv2dImplicitGEMM absolutely necessary?

### ISSUE THREAD

**Issue by Harvey-Mei** [DingXiaoH/RepLKNet-pytorch#16]
Hello DingXiao
Can we just use the Conv2D in torch? 
Are there other effects besides computational efficiency?

BR

**Comment by DingXiaoH** [comment]
Of course you can use nn.Conv2d. Our implementation is just faster.

**Comment by Harvey-Mei** [comment]
OK.
Thanks for your reply!
