### ISSUE TITLE
How to train on your own dataset

### ISSUE THREAD

**Issue by BainOuO** [DingXiaoH/RepLKNet-pytorch#19]
How to train on your own dataset

**Comment by DingXiaoH** [comment]
Training our models on another dataset is as easy as training any standard model (like ResNet-50) on another dataset.

**Comment by BainOuO** [comment]
thank you



---- Replied Message ----
| From | Xiaohan ***@***.***> |
| Date | 05/27/2022 00:26 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [DingXiaoH/RepLKNet-pytorch] How to train on your own dataset (Issue #19) |

Training our models on another dataset is as easy as training any standard model (like ResNet-50) on another dataset.
