### ISSUE TITLE
training for downstream task

### ISSUE THREAD

**Issue by thancaocuong** [DingXiaoH/RepLKNet-pytorch#22]
thank you for your nice work. I have one question for you that when training for the downstream tasks, the procedure is that training RepLKNet -> replace backbone on downstream task -> inference after re-params? is it right?

**Comment by DingXiaoH** [comment]
More precisely, pretraining RepLKNet -> replace backbone on downstream task (and load the pretrained model) -> train on the downstream task -> re-param after training -> deploy your model. If you only want to test the performance and do not care about the inference speed, there is no need to do the transformation (i.e., equivalently merge the small conv).
