### ISSUE TITLE
setup.py build error

### ISSUE THREAD

**Issue by carlsummer** [DingXiaoH/RepLKNet-pytorch#27]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xutility(4430): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std
::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\vector(1419): here
            instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, at::Tensor>::Item, _Alloc
=std::allocator<torch::OrderedDict<std::string, at::Tensor>::Item>]"
D:\env\pytorh\lib\site-packages\torch\include\torch/csrc/api/include/torch/ordered_dict.h(419): here
            instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=at::Tensor]"
D:\env\pytorh\lib\site-packages\torch\include\torch\csrc\api\include\torch/nn/modules/container/parameterdict.h(51): here

F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xutility(4430): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std
::string, std::shared_ptr<torch::nn::Module>>::Item &) [with Key=std::string, Value=std::shared_ptr<torch::nn::Module>]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, std::shared_ptr<torch::nn::Module>>::Item *, _OutIt=torch::OrderedDict<std::string
, std::shared_ptr<torch::nn::Module>>::Item *]"
F:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\vector(1419): here
            instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, std::shared_ptr<torch::nn
::Module>>::Item, _Alloc=std::allocator<torch::OrderedDict<std::string, std::shared_ptr<torch::nn::Module>>::Item>]"
D:\env\pytorh\lib\site-packages\torch\include\torch/csrc/api/include/torch/ordered_dict.h(419): here
            instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=std::shared_ptr<torch::nn::Module>]"
D:\env\pytorh\lib\site-packages\torch\include\torch\csrc\api\include\torch/nn/modules/container/moduledict.h(196): here

**Comment by DingXiaoH** [comment]
We have not tried windows. We would really appreciate it if you could share with us your solution.
