### ISSUE TITLE
RepLKNet-31L 21k weights seems to be wrong

### ISSUE THREAD

**Issue by shkarupa-alex** [DingXiaoH/RepLKNet-pytorch#3]
I've ported RepLKNet model to TF (will be published soon).
But during tests i've found that one particular checkpoint - RepLKNet-31L for imagenet21k - produces wrong predictions.

For image https://storage.googleapis.com/tensorflow/keras-applications/tests/elephant.jpg it predicts top-2 classes: 20104, 10871 which are "flowering_almond" and "strainer".

All other checkpoints for 1k and 21k imagenet predict correct classes (3674 for African_elephant in 21k)

**Comment by DingXiaoH** [comment]
The weights file may not have been well trained, but at least it worked reasonably on our downstream tasks... I guess it just happens to make a mistake on this picture?

**Comment by shkarupa-alex** [comment]
I think this is not just a mistake on particular picture.
Could you check predictions of this pytorch checkpoint with your eval pipeline?

**Comment by zhouyizhuang-megvii** [comment]
> I think this is not just a mistake on particular picture. Could you check predictions of this pytorch checkpoint with your eval pipeline?

The TF model might (see [timm vision_transformer](https://github.com/rwightman/pytorch-image-models/blob/07379c6d5dbb809b3f255966295a4b03f23af843/timm/models/vision_transformer.py#L117)) be trained on 21843 classes, while ours are pretrained on 21841 classes following FAIR and microsoft (see [BeiT](https://github.com/microsoft/unilm/blob/793d077c9769b0cc49ba6143f9e4310305bf362b/beit/README.md?plain=1#L147)). It seems google's imagenet22k is slightly different from ours, and a proper class mapping is likely to resolve this issue.

I think this discussion may help you find the 2 missing classes: https://github.com/google-research/big_transfer/issues/18
