### ISSUE TITLE
ERF small fix 

### ISSUE THREAD

**Issue by layumi** [DingXiaoH/RepLKNet-pytorch#31]
Thanks for the great code. 

https://github.com/DingXiaoH/RepLKNet-pytorch/blob/main/erf/analyze_erf.py#L60

The ((i*2+1)/1024) **2  can be modified to 
(i * 2 + 1) / h * (i * 2 + 1) / w  
making the code robust.

**Comment by DingXiaoH** [comment]
Updated. Many thanks!
