### ISSUE TITLE
About large depthwise conv2d kernel speed 

### ISSUE THREAD

**Issue by zzk2021** [DingXiaoH/RepLKNet-pytorch#47]
您好，我做了一个关于您提供的大卷积核算子速度的实验。对比pytorch的Conv2d

```
    if torch.cuda.is_available():
        x = torch.randn(64, 1000, 32, 32).cuda()
        x1 = torch.randn(64, 1000, 32, 32).cuda()
        m1 = DepthWiseConv2dImplicitGEMM(1000, 31, bias=False).cuda()
        m2 = nn.Conv2d(1000, 1000, 31, padding=31// 2, bias=False, groups=1000).cuda()
        
        start = time.time()
        y2 = m2(x1)
        y2.mean().backward()
        end = time.time()

        start1 = time.time()
        y1 = m1(x)
        y1.mean().backward()
        end1 = time.time()


        print("time:",end-start,end1-start1)
```
结果：
time: 0.0003426074981689453 0.0003437995910644531
经过测试，他们前向和后向所花费的时间几乎是相同的。是pytorch做了相关优化吗？
pytorch 1.9.0  python3.9  cuda 10.2

**Comment by klae01** [comment]
Compare time with torch.cuda.synchronize()

By the way, did you have any success with the installation?
I am failing to install in colab environment.
So I'm not sure if this answer will solve your problem.

**Comment by zzk2021** [comment]
Thanks. I try your method and It works.
real time:
Conv2d 1.4116837978363037 
DepthWiseConv2dImplicitGEMM 0.19309020042419434

For your question,actually I compiled with python 3.8.3  torch 1.8.0 cuda 10.2 
It stuck with pytorch 1.9.0 , anyway, I dont know why.

**Comment by zzk2021** [comment]
solved
Compare time with torch.cuda.synchronize()
thanks to klae01
