### ISSUE TITLE
Plug-and-play model

### ISSUE THREAD

**Issue by qdd1234** [DingXiaoH/RepLKNet-pytorch#6]
作者您好，感谢你们精彩的工作，我有一个疑问，您的paper中的大卷积核思想是否可以迁移到resnet中去替换resnet中的3*3卷积？谢谢

**Comment by megvii-model** [comment]
Sure. But please keep in mind that large kernels are more difficult to optimize. Therefore the modified ResNet may require to train with stronger augmentations, more epochs or larger pretrain datasets to obtain better performance.
