### ISSUE TITLE
Visualize the effective receptive field

### ISSUE THREAD

**Issue by DDxk369** [DingXiaoH/RepLKNet-pytorch#8]
大神您好，感谢您在重参数化方面的工作，我非常喜欢这篇文章，但同时我有个小问题，论文图一中关于有效感受野您是如何可视化的？如果方便的话能否将这段小code展示一下，相信能够帮助到很多像我这样刚入门的小白!  谢谢您

**Comment by DingXiaoH** [comment]
Hi, working on that.

**Comment by DDxk369** [comment]
太棒了，十分感谢！

**Comment by sleepat-11** [comment]
i  am wondering how to visualize the effective receptive field of vision transformer?

**Comment by DingXiaoH** [comment]
> 
how to visualize the effective receptive field of vision transformer?
You may use the same code we provided. Just modify your code of transformer to output its last feature maps (you may need to reshape from N(HW)C to NCHW).
