### ISSUE TITLE
The feasibility of using dilation kernels

### ISSUE THREAD

**Issue by seekFire** [DingXiaoH/RepLKNet-pytorch#9]
Thank you for your nice work!
You know, the large convolution kernel has too much parameters, which is constrained to be used in light model. So I think it is a good idea that replace large kernels with dilation kernels. For example, the 31x31 can be replaced with options as follows:
16x16, dilation=2
11x11, dilation=3
7x7, dilation=5, and etc.

**Comment by DingXiaoH** [comment]
Hi, thanks for the suggestions. We have not tried that, but I think it may work if the dilation rates are configured properly.
